project:
  type: book

book:
  title: "Guides for Advanced Statistical Inference"
  author: "Edda Brandes"
  date: "Summer 2023"
  cover-image: cover.png
  chapters:
    - index.qmd
    - multi-level.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

