project:
  type: book

book:
  title: "Guides for Advanced Statistical Inference"
  author: "Edda Brandes"
  date: "2023"
  chapters:
    - index.qmd
    - multi-level.qmd
    - panel_data.qmd
    - missing-data.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

